Evaluate: Check is the cliam is factually correct.


Instruction:
If the documents fully supports the claims : Yes.
If the document partially supports the claims, use the general knowledge the remaining information.
If the documents does not support the claims : No.
If no document is provides, rely on your own general knowledge.
If no document provide, please just say "Yes" or "No".

Document:
{document}

Claim:
{claim}



