This is about pickleball this is the most popular sports in the USA
Prived the dimension of the court, wequipent used and player format.
PickleBall Summary:
- The fane was found in 1965 and says the name came from a pet dog or boat used.
- The dimension of the  court 44 feet in length and 20 feet in widht.
- The accessories need to play is pickleball paddle and ball.
- 2 players can play single format and 4 players play the doubles format.