spring.application.name=springAI
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger){yellow} : %m%n
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:1b