spring.application.name=Tools
spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.docker.compose.stop.command=stop
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=naveenk
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update